import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"
# this makes sure the font DPR ratio is right for all devices
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMonoNerdFontMono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFontMono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNerdFontMono"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFontMono"
style = "Regular"
